name: Deploy Eswatini Droughtmap Hub to test environment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: src

      - name: Checkout Akvo composite actions
        uses: actions/checkout@v4
        with:
          repository: akvo/composite-actions
          token: ${{ secrets.GH_PAT }}
          path: composite-actions
          ref: main

      - name: Update App
        uses: ./composite-actions/.github/actions/ssh-command
        with:
          server-ip:  ${{ secrets.SERVER_IP }}
          server-ssh-port:  ${{ secrets.SERVER_SSH_PORT }}
          server-ssh-secret-key:  ${{ secrets.SERVER_SSH_SECRET_KEY }}
          server-ssh-user:  ${{ secrets.SERVER_SSH_USER }}
          command: ${{ secrets.COMMAND }}